### ISSUE TITLE
採用選擇題？

### ISSUE THREAD

**Issue by rniczh** [rust-tw/modernweb-booth-question#4]
e.g.
Q:
2019年 most loved language 是： 
1) 隔壁的 python 2) 隔壁的 js 3) 隔壁的 kotlin 4) 隔壁的php 5) Rust

A: 5

---

json 可以改成：
```
{ 
  "question": "2019年 most loved language 是： \n
1) 隔壁的 python 2) 隔壁的 js 3) 隔壁的 kotlin 4) 隔壁的php 5) Rust",

  "answer": 5
}
```
`main.rs` 的 subject 則是：
```
struct Subject {
    question: String,
    answer: u32,
}
```

**Comment by lili668668** [comment]
喔喔，我剛剛改完了，但 answer 還是 string，我想說之後還想要用簡答題也可以直接用 ((欸

**Comment by rniczh** [comment]
嗯嗯, String 的話還可以有簡答
